name: 'TODO: write action name'
description: 'TODO: write description'
author: 'gsoc2' # TODO: write your name.
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  repo:
    description: 'target GitHub repository. e.g. reviewdog/reviewdog'
    default: '${{ github.repository }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://gsoc2.github.io/github-action-brandings/
# TODO: update branding.
branding:
  icon: 'activity'
  color: 'white'
